spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/users
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret-key: 578KdC9YSr7/bAppwuooZwNjUvqxuvRgPNtKTprXDzM= # don't worry some random dumbass key
  expiration-hr: 1